spring.application.name=demo

spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:3306/mysql
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#jwt settings
jobTracker.app.jwtSecret=jwt.secret=${JWT_SECRET:f6PCcV8BlhrgLhI5mUQgVCptWXvck4Xcv1v1hnchQC4=}
jobTracker.app.jwtExpirationsMs=86400000

# Microsoft Graph API Connection Keys
microsoft.graph.tenantId=${GRAPH_TENANT_ID}
microsoft.graph.clientId=${GRAPH_CLIENT_ID}
microsoft.graph.clientSecret=${GRAPH_CLIENT_SECRET}

# The specific business email inbox you want to read inside your app
microsoft.graph.targetMailbox=${GRAPH_TARGET_MAILBOX}

aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.s3.region=${AWS_REGION}
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
